services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./backend:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "php artisan migrate --force && php-fpm"

  controller:
    image: nginx:latest
    container_name: controller
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  database:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: appuser
      PMA_PASSWORD: apppassword
    depends_on:
      database:
        condition: service_healthy

volumes:
  dbdata:
